openapi: 3.2.0
info:
  title: VTex Catalog Similar Category API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Similar Category
paths:
  /api/catalog/pvt/product/{productId}/similarcategory/:
    get:
      tags:
      - Similar Category
      summary: VTex Get similar categories
      description: 'Retrieves similar categories from a product.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Similar Category** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: productId
        in: path
        required: true
        description: Product's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
              - ProductId: 1
                CategoryId: 1
              - ProductId: 1
                CategoryId: 20
              schema:
                type: array
                description: Array of objects with similar category information.
                items:
                  type: object
                  description: Object containing product ID and similar category ID.
                  properties:
                    ProductId:
                      type: integer
                      description: Product ID.
                      example: 1
                    CategoryId:
                      type: integer
                      description: Similar category ID.
                      example: 20
      operationId: getApiCatalogPvtProductByProductIdSimilarcategory
      x-operation-id-source: derived
  /api/catalog/pvt/product/{productId}/similarcategory/{categoryId}:
    post:
      tags:
      - Similar Category
      summary: VTex Add similar category
      description: 'Adds a similar category to a product.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Similar Categories Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: productId
        in: path
        required: true
        description: Product's unique numerical identifier.
        schema:
          type: integer
          example: 1
      - name: categoryId
        in: path
        required: true
        description: Similar category's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                ProductId: 1
                StoreId: 1
              schema:
                type: object
                description: Object containing information related to the similar category.
                properties:
                  ProductId:
                    type: integer
                    description: Product ID.
                    example: 1
                  StoreId:
                    type: integer
                    description: Trade policy ID.
                    example: 1
      operationId: postApiCatalogPvtProductByProductIdSimilarcategoryByCategoryId
      x-operation-id-source: derived
    delete:
      tags:
      - Similar Category
      summary: VTex Delete similar category
      description: 'Deletes a similar category from a product.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Similar Categories Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: productId
        in: path
        required: true
        description: Product's unique numerical identifier.
        schema:
          type: integer
          example: 1
      - name: categoryId
        in: path
        required: true
        description: Similar category's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtProductByProductIdSimilarcategoryByCategoryId
      x-operation-id-source: derived
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
