openapi: 3.2.0
info:
  title: VTex Marketplace Sales Channel Mapping API
  description: The **Marketplace API** enables marketplaces and sellers hosted on VTEX to perform their collaborative operations.
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br/api
  description: VTEX Server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Sales Channel Mapping
paths:
  /seller-register/pvt/sellers/{sellerId}/sales-channel/mapping:
    put:
      tags:
      - Sales Channel Mapping
      summary: VTex Upsert Sales Channel Mapping
      description: This endpoint allows the marketplace to map its sales channels with a seller's affiliate. The seller can have multiple sales channels associated with the same marketplace, by creating different affiliates. The mapping enables the seller to segment catalog, prices, inventory, logistics, and payments in the marketplace.
      operationId: UpsertMapping
      parameters:
      - $ref: '#/components/parameters/contentType'
      - $ref: '#/components/parameters/accept'
      - $ref: '#/components/parameters/accountName'
      - $ref: '#/components/parameters/environment'
      - $ref: '#/components/parameters/an'
      - $ref: '#/components/parameters/sellerId'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpsertMappingRequest'
              example:
              - marketplaceSalesChannel: 1
                sellerChannel: GCB
              - marketplaceSalesChannel: 2
                sellerChannel: GCB
            example:
            - marketplaceSalesChannel: 1
              sellerChannel: GCB
            - marketplaceSalesChannel: 2
              sellerChannel: GCB
        required: true
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    marketplaceSalesChannel:
                      type: string
                      description: Marketplace's sales channel that will be associated to the seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187).
                      default: '1'
                    sellerChannel:
                      type: string
                      description: Seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187) that will be associated with the marketplace's sales channel. Through the affiliate, the seller determines which of his sales channel will be used for the mapping.
                      default: GCB
                title: UpsertMapping
                example:
                - marketplaceSalesChannel: '1'
                  sellerChannel: GCC
                properties:
                  marketplaceSalesChannel:
                    type: integer
                    description: Marketplace's sales channel that will be associated to the seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187).
                    default: 1
                  sellerChannel:
                    type: string
                    description: Seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187) that will be associated with the marketplace's sales channel. Through the affiliate, the seller determines which of his sales channel will be used for the mapping.
                    default: GCB
      deprecated: false
    get:
      tags:
      - Sales Channel Mapping
      summary: VTex Get Sales Channel Mapping Data
      description: Retrieves information about the mapping between marketplace's sales channels and a specific seller.
      operationId: RetrieveMapping
      parameters:
      - $ref: '#/components/parameters/contentType'
      - $ref: '#/components/parameters/accept'
      - $ref: '#/components/parameters/accountName'
      - $ref: '#/components/parameters/environment'
      - $ref: '#/components/parameters/an'
      - $ref: '#/components/parameters/sellerId'
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    marketplaceSalesChannel:
                      type: string
                      description: Marketplace's sales channel that will be associated to the seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187).
                      default: '1'
                    sellerChannel:
                      type: string
                      description: Seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187) that will be associated with the marketplace's sales channel. Through the affiliate, the seller determines which of his sales channel will be used for the mapping.
                      default: GCB
                title: UpsertMapping
                example:
                - marketplaceSalesChannel: '1'
                  sellerChannel: GCC
                properties:
                  marketplaceSalesChannel:
                    type: integer
                    description: Marketplace's sales channel that will be associated to the seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187).
                    default: 1
                  sellerChannel:
                    type: string
                    description: Seller's [affiliate](https://help.vtex.com/en/tutorial/configuring-affiliates--tutorials_187) that will be associated with the marketplace's sales channel. Through the affiliate, the seller determines which of his sales channel will be used for the mapping.
                    default: GCB
      deprecated: false
components:
  parameters:
    accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    contentType:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    environment:
      name: environment
      in: path
      required: true
      description: Environment to use. Used as part of the URL.
      schema:
        type: string
        default: vtexcommercestable
    accountName:
      name: accountName
      in: path
      required: true
      description: Name of the VTEX account that belongs to the marketplace. The notification will be posted into this account.
      schema:
        type: string
        example: apiexamples
    sellerId:
      name: sellerId
      in: path
      description: A string that identifies the seller in the marketplace. This ID must be created by the marketplace and informed to the seller before the integration is built.
      required: true
      style: simple
      schema:
        type: string
        example: seller123
    an:
      name: an
      in: query
      description: Marketplace's account name, the same one inputted on the endpoint's path.
      required: true
      style: form
      explode: true
      schema:
        type: string
        default: apiexamples
  schemas:
    UpsertMappingRequest:
      description: Request to upsert a mapping between a marketplace's sales channel and a seller's affiliate.
      required:
      - marketplaceSalesChannel
      - sellerChannel
      type: object
      properties:
        marketplaceSalesChannel:
          type: integer
          description: The sales channel of the marketplace to be associated with the seller's affiliate. It is linked to the seller's affiliate.
          example: 1
        sellerChannel:
          type: string
          description: The affiliate of the seller that will be associated with the marketplace's sales channel. Through the affiliate, the seller determines which of his sales channels will be used for the mapping.
          example: GCB
      example:
        marketplaceSalesChannel: 1
        sellerChannel: GCB
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
