openapi: 3.2.0
info:
  title: VTex Marketplace Seller Commissions API
  description: The **Marketplace API** enables marketplaces and sellers hosted on VTEX to perform their collaborative operations.
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br/api
  description: VTEX Server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Seller Commissions
paths:
  /seller-register/pvt/sellers/{sellerId}/commissions:
    get:
      tags:
      - Seller Commissions
      summary: VTex List Seller Commissions by seller ID
      description: 'This endpoint retrieves all comissions configured for a specific seller. It is not necessary to send a request body.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** | **Role** |

        |---|---|---|---|

        | Seller Register | Seller adminstration | View Seller | View all sellers linked to the Marketplace account described on the sellers management page, including recovering seller data, either from the sellers listing, or a specific seller. |

        | Seller Register | Seller administration | Save Seller | Create new sellers and edit data from all sellers linked to Marketplace account from the sellers management page. |


        You can create a custom role with this feature or use one of the predefined roles from the list above.


        >❗ Assigning a predefined role to users or application keys usually grants permission to multiple License Manager resources. If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see Best practices for using application keys. To learn more about machine authentication at VTEX, see Authentication overview.'
      operationId: ListSellerCommissions
      parameters:
      - $ref: '#/components/parameters/accountName'
      - $ref: '#/components/parameters/environment'
      - $ref: '#/components/parameters/sellerId'
      - $ref: '#/components/parameters/accept'
      - $ref: '#/components/parameters/contentType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array with objects containing information about the category, seller and percentage of commission applied.
                items:
                  $ref: '#/components/schemas/responseSellerCommissionsID'
      deprecated: false
    put:
      tags:
      - Seller Commissions
      summary: VTex Upsert Seller Commissions in bulk
      description: 'This endpoint is used by marketplace operators to define comissions for multiple categories, sending an array with multiple objects in the same call.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** | **Role** |

        |----|----|----|----|

        | Seller Register | Seller administration | Save Seller | Create new sellers and edit data from all sellers linked to Marketplace account from the sellers management page. |


        You can create a custom role with this feature or use one of the predefined roles from the list above.


        >❗ Assigning a predefined role to users or application keys usually grants permission to multiple License Manager resources. If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see Best practices for using application keys. To learn more about machine authentication at VTEX, see Authentication overview.'
      operationId: BulkUpsertSellerCommissions
      parameters:
      - $ref: '#/components/parameters/accountName'
      - $ref: '#/components/parameters/environment'
      - $ref: '#/components/parameters/accept'
      - $ref: '#/components/parameters/contentType'
      - $ref: '#/components/parameters/sellerId'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              description: Array with objects containing information about the category, seller and commission percentage to be applied.
              items:
                $ref: '#/components/schemas/BulkUpsertSellerCommissionsRequest'
        required: true
      responses:
        '204':
          description: No Content
      deprecated: false
  /seller-register/pvt/sellers/{sellerId}/commissions/{categoryId}:
    delete:
      tags:
      - Seller Commissions
      summary: VTex Remove Seller Commissions by Category ID
      operationId: RemoveSellerCommissions
      description: 'This endpoint removes a seller comission on the selected category.


        >❗This action cannot be undone, to reconfigure the commission it is necessary to use the Upsert Seller Commissions in Bulk endpoint.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** | **Role** |

        |----|----|----|----|

        | Seller Register | Seller administration | Save Seller | Create new sellers and edit data from all sellers linked to Marketplace account from the sellers management page. |


        You can create a custom role with this feature or use one of the predefined roles from the list above.


        >❗ Assigning a predefined role to users or application keys usually grants permission to multiple License Manager resources. If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see Best practices for using application keys. To learn more about machine authentication at VTEX, see Authentication overview.'
      parameters:
      - $ref: '#/components/parameters/accountName'
      - $ref: '#/components/parameters/environment'
      - $ref: '#/components/parameters/accept'
      - $ref: '#/components/parameters/contentType'
      - $ref: '#/components/parameters/sellerId'
      - $ref: '#/components/parameters/categoryId'
      responses:
        '204':
          description: No Content
      deprecated: false
    get:
      tags:
      - Seller Commissions
      summary: VTex Get Seller Commissions by Category ID
      operationId: RetrieveSellerCommissions
      description: 'This endpoint retrieves seller comissions applied to the selected category. It is not necessary to send a request body.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** | **Role** |

        |---|---|---|---|

        | Seller Register | Seller adminstration | View Seller | View all sellers linked to the Marketplace account described on the sellers management page, including recovering seller data, either from the sellers listing, or a specific seller. |

        | Seller Register | Seller administration | Save Seller | Create new sellers and edit data from all sellers linked to Marketplace account from the sellers management page. |


        You can create a custom role with this feature or use one of the predefined roles from the list above.


        >❗ Assigning a predefined role to users or application keys usually grants permission to multiple License Manager resources. If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see Best practices for using application keys. To learn more about machine authentication at VTEX, see Authentication overview.'
      parameters:
      - name: accountName
        in: path
        description: Name of the VTEX account that belongs to the marketplace. All data extracted, and changes added will be posted into this account.
        required: true
        schema:
          type: string
          default: apiexamples
      - name: environment
        in: path
        required: true
        description: Environment to use. Used as part of the URL.
        schema:
          type: string
          default: vtexcommercestable
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        description: Describes the type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: sellerId
        in: path
        description: A string that identifies the seller in the marketplace. This ID must be created by the marketplace.
        required: true
        style: simple
        schema:
          type: string
          default: seller123
      - name: categoryId
        in: path
        description: ID of the category in which the comission was applied
        required: true
        style: simple
        schema:
          type: string
          default: '6'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseSellerCommissionsID'
      deprecated: false
components:
  parameters:
    accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    categoryId:
      name: categoryId
      in: path
      description: ID of the category in which the comission was applied
      required: true
      style: simple
      schema:
        type: string
        default: '6'
    contentType:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    environment:
      name: environment
      in: path
      required: true
      description: Environment to use. Used as part of the URL.
      schema:
        type: string
        default: vtexcommercestable
    accountName:
      name: accountName
      in: path
      required: true
      description: Name of the VTEX account that belongs to the marketplace. The notification will be posted into this account.
      schema:
        type: string
        example: apiexamples
    sellerId:
      name: sellerId
      in: path
      description: A string that identifies the seller in the marketplace. This ID must be created by the marketplace and informed to the seller before the integration is built.
      required: true
      style: simple
      schema:
        type: string
        example: seller123
  schemas:
    BulkUpsertSellerCommissionsRequest:
      required:
      - categoryId
      - categoryFullPath
      - productCommissionPercentage
      - freightCommissionPercentage
      type: object
      properties:
        categoryId:
          type: string
          description: Marketplace's Category ID that the product belongs to, configured in the Catalog.
          example: '6'
        categoryFullPath:
          type:
          - string
          - 'null'
          description: 'Full path to the SKU''s category. It should be written as {department}/{category}. For example: if the department is **Appliances** and the category is **Oven**, the full path should be ''Appliances/Oven''.'
          example: Appliances/Oven
        productCommissionPercentage:
          type: number
          description: Percentage of the comission applied to the product in decimals.
          example: 9.85
        freightCommissionPercentage:
          type: number
          description: Percentage of the comission applied to the freight in decimals.
          example: 2.43
      example:
      - categoryId: '6'
        categoryFullPath: null
        productCommissionPercentage: 9.85
        freightCommissionPercentage: 2.43
      - categoryId: '51'
        categoryFullPath: Appliances/Oven
        productCommissionPercentage: 7.85
        freightCommissionPercentage: 3.43
    responseSellerCommissionsID:
      type: object
      description: Object with the category properties and the commission percentage applied to it.
      properties:
        categoryId:
          type: string
          description: Marketplace's Category ID that the product belongs to, configured in the Catalog.
          example: '51'
        categoryName:
          type: string
          description: Category name with applied commission.
          example: Clothes
        categoryFullPath:
          type: array
          description: Full path to the SKU's category.
          items:
            type: string
            example: '2.0'
          example:
          - '2.0'
          - Boys
          - Clothes
        productCommissionPercentage:
          type: number
          description: Percentage of the comission applied to the product in decimals.
          example: 7.75
        freightCommissionPercentage:
          type: number
          description: Percentage of the comission applied to the freight in decimals.
          example: 2.33
      example:
        categoryId: '51'
        categoryName: Clothes
        categoryFullPath:
        - '2.0'
        - Boys
        - Clothes
        productCommissionPercentage: 7.75
        freightCommissionPercentage: 2.33
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
