openapi: 3.2.0
info:
  title: VTex Catalog SKU Complement API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: SKU Complement
paths:
  /api/catalog/pvt/stockkeepingunit/{skuId}/complement:
    get:
      tags:
      - SKU Complement
      summary: VTex Get SKU complement by SKU ID
      description: 'Retrieves an existing SKU complement by its SKU ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: GetSKUComplementbySKUID
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuComplement'
              example:
              - Id: 61
                SkuId: 7
                ParentSkuId: 1
                ComplementTypeId: 1
  /api/catalog/pvt/stockkeepingunit/{skuId}/complement/{complementTypeId}:
    get:
      tags:
      - SKU Complement
      summary: VTex Get SKU complements by complement type ID
      description: 'Retrieves all the existing SKU complements with the same complement type ID of a specific SKU.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: GetSKUComplementsbyComplementTypeID
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: ID of the SKU which will be inserted as a complement in the parent SKU.
        schema:
          type: integer
          example: 1
      - name: complementTypeId
        in: path
        required: true
        description: 'Complement type ID. This represents the type of the complement. The possible values are: `1` for **Accessory**; `2` for **Suggestion**; `3` for **Similar product**; `5` for **Show together**.'
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuComplement'
              example:
              - Id: 61
                SkuId: 7
                ParentSkuId: 1
                ComplementTypeId: 1
  /api/catalog_system/pvt/sku/complements/{parentSkuId}/{type}:
    get:
      tags:
      - SKU Complement
      summary: VTex Get SKU complements by type
      description: 'Retrieves all the existing SKU complements with the same complement type ID of a specific SKU and parent SKU ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: GetSKUcomplementsbytype
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: parentSkuId
        in: path
        required: true
        description: ID of the parent SKU, where the complement is inserted.
        schema:
          type: integer
          example: 1
      - name: type
        in: path
        required: true
        description: 'Complement type ID. This represents the type of the complement. The possible values are: `1` for **Accessory**; `2` for **Suggestion**; `3` for **Similar product**; `5` for **Show together**.'
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                ParentSkuId: 1
                ComplementSkuIds:
                - 7
                Type: '1'
              schema:
                type: object
                required:
                - ParentSkuId
                - ComplementSkuIds
                - Type
                properties:
                  ParentSkuId:
                    type: integer
                    description: ID of the parent SKU, where the complement is inserted.
                  ComplementSkuIds:
                    type: array
                    description: Array with SKU complements IDs.
                    items:
                      type: integer
                      description: SKU complement ID.
                  Type:
                    type: string
                    description: 'Complement type ID. This represents the type of the complement. The possible values are: `1` for **Accessory**; `2` for **Suggestion**; `3` for **Similar product**; `5` for **Show together**.'
                    enum:
                    - '1'
                    - '2'
                    - '3'
                    - '4'
                    - '5'
  /api/catalog/pvt/skucomplement:
    post:
      tags:
      - SKU Complement
      summary: VTex Create SKU complement
      description: 'Creates a new SKU complement on a parent SKU.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: CreateSKUComplement
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            example:
              ParentSkuId: 1
              SkuId: 2
              ComplementTypeId: 2
            schema:
              type: object
              required:
              - ParentSkuId
              - SkuId
              - ComplementTypeId
              properties:
                ParentSkuId:
                  type: integer
                  description: ID of the parent SKU, where the complement is inserted.
                  example: 1
                SkuId:
                  type: integer
                  description: ID of the SKU which will be inserted as a complement in the parent SKU.
                  example: 1
                ComplementTypeId:
                  type: integer
                  description: 'Complement type ID. This represents the type of the complement. The possible values are: `1` for **Accessory**; `2` for **Suggestion**; `3` for **Similar product**; `5` for **Show together**.'
                  example: 1
                  enum:
                  - 1
                  - 2
                  - 3
                  - 4
                  - 5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuComplement'
              example:
              - Id: 61
                SkuId: 7
                ParentSkuId: 1
                ComplementTypeId: 1
  /api/catalog/pvt/skucomplement/{skuComplementId}:
    get:
      tags:
      - SKU Complement
      summary: VTex Get SKU complement by SKU complement ID
      description: 'Retrieves an existing SKU complement by its SKU complement ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: GetSKUComplementbySKUComplementID
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuComplementId
        in: path
        required: true
        description: SKU complement's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuComplement'
              example:
              - Id: 61
                SkuId: 7
                ParentSkuId: 1
                ComplementTypeId: 1
    delete:
      tags:
      - SKU Complement
      summary: VTex Delete SKU complement by SKU complement ID
      description: 'Deletes a previously existing SKU complement by SKU complement ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: DeleteSKUComplementbySKUComplementID
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuComplementId
        in: path
        required: true
        description: SKU complement's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  schemas:
    SkuComplement:
      required:
      - Id
      - SkuId
      - ParentSkuId
      - ComplementTypeId
      type: array
      items:
        type: object
        properties:
          Id:
            type: integer
            description: SKU complement's unique numerical identifier.
          SkuId:
            type: integer
            description: ID of the SKU which will be inserted as a complement in the parent SKU.
          ParentSkuId:
            type: integer
            description: ID of the parent SKU, where the complement will be inserted.
          ComplementTypeId:
            type: integer
            description: 'Complement type ID. This represents the type of the complement. The possible values are: `1` for **Accessory**; `2` for  **Suggestion**; `3` for **Similar product**; `5` for **Show together**.'
            enum:
            - 1
            - 2
            - 3
            - 4
            - 5
      example:
      - Id: 61
        SkuId: 7
        ParentSkuId: 1
        ComplementTypeId: 1
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
