openapi: 3.2.0
info:
  title: VTex Logistics Polygons API
  description: "\n\n>Check the [Fulfillment onboarding guide](https://developers.vtex.com/docs/guides/fulfillment). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about fulfillment and is organized by focusing on the developer's journey.\n\nLogistics or fulfillment is the module responsible for shipping calculation and inventory management. \n\nThe variable `{{environment}}` can be filled with `vtexcommercestable` or `vtexcommercebeta`, depending on the environment you want to test."
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Polygons
paths:
  /api/logistics/pvt/configuration/geoshape:
    get:
      tags:
      - Polygons
      summary: VTex List paged polygons
      description: Lists stored polygons.
      operationId: PagedPolygons
      parameters:
      - name: page
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: '{{page}}'
      - name: perPage
        in: query
        description: ''
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: '{{perPage}}'
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
    put:
      tags:
      - Polygons
      summary: VTex Create/update polygon
      description: Creates or updates your store's polygons by geoshape coordinates and polygon name.
      operationId: CreateUpdatePolygon
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              title: Create/UpdatePolygonRequest
              required:
              - name
              - geoShape
              type: object
              properties:
                name:
                  type: string
                geoShape:
                  title: GeoShape
                  required:
                  - coordinates
                  type: object
                  properties:
                    coordinates:
                      type: array
                      items:
                        type: array
                        items:
                          type: number
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/configuration/geoshape/{polygonName}:
    get:
      tags:
      - Polygons
      summary: VTex List polygon by ID
      description: Lists your store's polygons by searching through polygon name
      operationId: PolygonbyId
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: polygonName
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
    delete:
      tags:
      - Polygons
      summary: VTex Delete polygon
      description: Deletes polygon set up in your store, by polygon name.
      operationId: DeletePolygon
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: polygonName
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
components:
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
