openapi: 3.0.0
info:
  title: VTex Anti-fraud Provider Account Scheduled Delivery API
  description: ">ℹ️ Onboarding guide\r\n>\r\n> Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Payments and is organized by focusing on the developer's journey.\r\n\r\nThe Anti-fraud Provider Protocol is a set of definitions to help you integrate your anti-fraud service API into VTEX platform.\r\n\r\nTo achieve this, you need to implement a web API (REST) following the specifications described in this documentation.\r\n\r\n>⚠️ You can also access our [template on GitHub](https://github.com/vtex-apps/antifraud-provider-example) to help you quickly develop your anti-fraud connector using the Anti-fraud Provider Protocol and VTEX IO.\r\n\r\nTo learn more about the Anti-fraud Provider Protocol, check our [developer guide](https://developers.vtex.com/docs/guides/how-the-integration-protocol-between-vtex-and-antifraud-companies-works).\r\n\r\n## Anti-fraud Provider API Index\r\n\r\n### Anti-fraud  Flow\r\n\r\n- `POST` [Send Anti-fraud Pre-Analysis Data (optional)](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#post-/pre-analysis)\r\n- `POST` [Send Anti-fraud Data](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#post-/transactions)\r\n- `PUT` [Update Anti-fraud Transactions (optional)](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#put-/transactions/-transactionId-)\r\n- `GET` [List Anti-fraud Provider Manifest](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/manifest)\r\n- `GET` [Get Anti-fraud Status](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/transactions/-transactions.id-)\r\n- `DELETE` [Stop Anti-fraud Analysis (optional)](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#delete-/transactions/-transactions.Id-)\r\n\r\n### OAuth Flow\r\n\r\n1. `POST` [Retrieve Token](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#post-/authorization/token)\r\n2. `GET` [Redirect](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/redirect)\r\n3. `GET` [Return to VTEX](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/authorizationCode)\r\n4. `GET` [Get Credentials](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/authorization/credentials)"
  version: '1.0'
servers:
- url: https://{providerApiEndpoint}
  description: Anti-fraud provider endpoint URL.
  variables:
    providerApiEndpoint:
      description: Anti-fraud provider endpoint URL.
      default: '{providerApiEndpoint}'
tags:
- name: Scheduled Delivery
paths:
  /api/logistics/pvt/configuration/carriers/{carrierId}/getdayofweekblocked:
    get:
      tags:
      - Scheduled Delivery
      summary: VTex Retrieve blocked delivery windows
      description: "Lists all blocked delivery windows of your store's shipping policies, searching by carrier ID.\n\r\n\r> Note that, while most of our API endpoints return time fields in UTC, this endpoint returns **Scheduled Delivery** related time fields adjusted to the configured time zone of the account."
      operationId: RetrieveBlockedDeliveryWindows
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: carrierId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
      deprecated: false
  /api/logistics/pvt/configuration/carriers/{carrierId}/adddayofweekblocked:
    post:
      tags:
      - Scheduled Delivery
      summary: VTex Add blocked delivery windows
      description: "Adds blocked delivery windows for your store's shipping policies.\n\r\n\r> Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account."
      operationId: AddBlockedDeliveryWindows
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: carrierId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              type: string
              example: '"2016-08-09T08:00:00"'
            example: '"2016-08-09T08:00:00"'
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/configuration/carriers/{carrierId}/removedayofweekblocked:
    post:
      tags:
      - Scheduled Delivery
      summary: VTex Remove blocked delivery windows
      description: "Removes the blocked delivery windows set to your store's shipping policies.\n\r\n\r> Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account."
      operationId: RemoveBlockedDeliveryWindows
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: carrierId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              type: string
              example: '"2016-08-09T08:00:00"'
            example: '"2016-08-09T08:00:00"'
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics-capacity/resources/carrier@{capacityType}@{shippingPolicyId}/time-frames:
    get:
      tags:
      - Scheduled Delivery
      summary: VTex Search capacity reservations in time range
      description: "Get information on all capacity reservations made to scheduled delivery windows in a given time range.\n\r\n\r> Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account.\n\r\n\r> Note that the combined string `carrier@{capacityType}@{shippingPolicyId}` can be referred to as a \"resource\" in the API's messages."
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/vnd.vtex.availability.v1+json
      - name: capacityType
        in: path
        description: How the delivery capacity is measured as defined in the shipping policy. Capacity can be measured by maximum number of orders (`"orders_quantity"`) or SKUs (`"skus_quantity"`).
        required: true
        style: simple
        schema:
          type: string
          example: '{{capacityType}}'
      - name: shippingPolicyId
        in: path
        description: ID of shipping policy to search.
        required: true
        style: simple
        schema:
          type: string
          example: '{{shippingPolicyId}}'
      - name: rangeStart
        in: query
        description: Starting date of time range
        required: true
        style: form
        schema:
          type: string
          example: yyyy-mm-dd
      - name: rangeEnd
        in: query
        description: End date of time range.
        required: true
        style: form
        schema:
          type: string
          example: yyyy-mm-dd
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                id: 2021-05-03F1300T1700
                resourceId: carrier@skus_quantity@143e313
                startDate: '2021-05-03T13:00:00+00:00'
                endDate: '2021-05-03T17:00:59+00:00'
                ownMaxCapacity: 10
                resourceMaxCapacity: 10
                reservedValue: 6
                reservations:
                - id: reservation-01
                  value: 4
                - id: reserva-02
                  value: 2
                log:
                - when: '2021-04-29T15:56:09.1732357+00:00'
                  who: ''
                  why: Reservation `reservation-01` with 2.0 units.
                  what: Unblocked
                - when: '2021-04-29T17:29:11.9250354+00:00'
                  who: ''
                  why: Reservation `reserva-02` with 4.0 units.
                  what: Unblocked
      deprecated: false
  ? /api/logistics-capacity/resources/carrier@{capacityType}@{shippingPolicyId}/time-frames/{windowDay}F{windowStartTime}T{windowEndTime}
  : get:
      tags:
      - Scheduled Delivery
      summary: VTex Get capacity reservation usage by window
      description: "Retrieves capacity usage of a specific scheduled delivery reservation window.\n\r\n\r> Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account.\n\r\n\r> Note that the combined string `carrier@{capacityType}@{shippingPolicyId}` can be referred to as a \"resource\" in the API's messages."
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/vnd.vtex.availability.v1+json
      - name: capacityType
        in: path
        description: How the delivery capacity is measured as defined in the shipping policy. Capacity can be measured by maximum number of orders (`"orders_quantity"`) or SKUs (`"skus_quantity"`).
        required: true
        style: simple
        schema:
          type: string
          example: '{{capacityType}}'
      - name: shippingPolicyId
        in: path
        description: ID of shipping policy to search.
        required: true
        style: simple
        schema:
          type: string
          example: '{{shippingPolicyId}}'
      - name: windowDay
        in: path
        description: Day of the specific scheduled delivery window to be consulted for reservations.
        required: true
        style: simple
        schema:
          type: string
          example: yyyy-mm-dd
      - name: windowStartTime
        in: path
        description: Start time of specific scheduled delivery window to be consulted for reservations.
        required: true
        style: simple
        schema:
          type: string
          example: hhmm
      - name: windowEndTime
        in: path
        description: End time of specific scheduled delivery window to be consulted for reservations.
        required: true
        style: simple
        schema:
          type: string
          example: hhmm
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                id: 2021-05-03F1300T1700
                resourceId: carrier@skus_quantity@143e313
                startDate: '2021-05-03T13:00:00+00:00'
                endDate: '2021-05-03T17:00:59+00:00'
                ownMaxCapacity: 10
                resourceMaxCapacity: 10
                reservedValue: 4
                reservations:
                - id: reservation-01
                  value: 4
                log:
                - when: '2021-04-29T15:56:09.1732357+00:00'
                  who: ''
                  why: Reservation `reservation-01` with 4 units.
                  what: Unblocked
      deprecated: false
components:
  securitySchemes:
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
