openapi: 3.2.0
info:
  title: VTex Catalog Attachment API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Attachment
paths:
  /api/catalog/pvt/attachment/{attachmentid}:
    get:
      tags:
      - Attachment
      summary: VTex Get attachment by ID
      description: 'Gets information about a registered attachment.

        >⚠️ To understand the specific syntax for Assembly Options attachments, read the Assembly Options documentation.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Configuration | **CMS Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - name: attachmentid
        in: path
        required: true
        description: Attachment ID.
        schema:
          type: string
          example: '8'
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResponse'
      operationId: getApiCatalogPvtAttachmentByAttachmentid
      x-operation-id-source: derived
    put:
      tags:
      - Attachment
      summary: VTex Update attachment
      description: 'Updates a previously existing SKU attachment with new information.

        >⚠️ To understand the specific syntax for Assembly Options attachments, read the Assembly Options documentation.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Configuration | **CMS Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - name: attachmentid
        in: path
        required: true
        description: Attachment ID.
        schema:
          type: string
          example: vtexcommercestable
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttachmentRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResponse'
      operationId: putApiCatalogPvtAttachmentByAttachmentid
      x-operation-id-source: derived
    delete:
      tags:
      - Attachment
      summary: VTex Delete attachment
      description: 'Deletes a previously existing SKU attachment.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Configuration | **CMS Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - name: attachmentid
        in: path
        required: true
        description: Attachment ID.
        schema:
          type: string
          example: vtexcommercestable
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtAttachmentByAttachmentid
      x-operation-id-source: derived
  /api/catalog/pvt/attachment:
    post:
      tags:
      - Attachment
      summary: VTex Create attachment
      description: 'Creates a new SKU attachment.

        >⚠️ To understand the specific syntax for Assembly Options attachments, read the Assembly Options documentation.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Configuration | **CMS Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttachmentRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttachmentResponse'
      operationId: postApiCatalogPvtAttachment
      x-operation-id-source: derived
  /api/catalog/pvt/attachments:
    get:
      tags:
      - Attachment
      summary: VTex Get all attachments
      description: 'Retrieves information about all registered attachments.

        >⚠️ To understand the specific syntax for Assembly Options attachments, read the Assembly Options documentation.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Configuration | **CMS Management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Page:
                    type: integer
                    description: Current page of results.
                    example: 1
                  Size:
                    type: integer
                    description: Total number of results in the current page.
                    example: 11
                  TotalRows:
                    type: integer
                    description: Total number of rows with results.
                    example: 11
                  TotalPage:
                    type: integer
                    description: Total number of pages with results.
                    example: 1
                  Data:
                    type: array
                    description: Array containing attachments data.
                    items:
                      $ref: '#/components/schemas/AttachmentResponse'
      operationId: getApiCatalogPvtAttachments
      x-operation-id-source: derived
components:
  schemas:
    AttachmentResponse:
      type: object
      required:
      - Id
      - Name
      - IsRequired
      - IsActive
      - Domains
      properties:
        Id:
          type: integer
          description: Attachment ID.
          example: 8
        Name:
          type: string
          description: Attachment name.
          example: Shirt customization
        IsRequired:
          type: boolean
          description: Defines if the attachment is required or not.
          example: false
        IsActive:
          type: boolean
          description: Defines if the attachment is active or not.
          example: false
        Domains:
          type: array
          description: List of characteristics related to the attachment.
          items:
            type: object
            properties:
              FieldName:
                type: string
                description: Attachment key name.
                example: Number
              MaxCaracters:
                type: string
                description: Maximum number of characters in the attachment key.
                example: '1'
              DomainValues:
                type: string
                description: Allowed key values.
                example: 7,9,10
      example:
        Id: 8
        Name: Ingredients
        IsRequired: true
        IsActive: true
        Domains:
        - FieldName: Sauce
          MaxCaracters: ''
          DomainValues: '[1-2]#9[1-1][1]basic;#11[0-1][1]basic'
        - FieldName: Toppings
          MaxCaracters: ''
          DomainValues: '[0-10]#8[0-3][0]medium;#9[0-3][0]medium;#10[0-3][0]medium;#11[0-3][0]medium;#36[0-3][0]medium;#37[0-3][0]medium;#38[0-3][0]medium'
    AttachmentRequest:
      type: object
      required:
      - Name
      - IsRequired
      - IsActive
      - Domains
      properties:
        Name:
          type: string
          description: Attachment name.
          example: Shirt customization
        IsRequired:
          type: boolean
          description: Defines if the attachment is required or not.
          example: false
        IsActive:
          type: boolean
          description: Defines if the attachment is active or not.
          example: false
        Domains:
          type: array
          description: List of characteristics related to the attachment.
          items:
            type: object
            properties:
              FieldName:
                type: string
                description: Attachment key name.
                example: Number
              MaxCaracters:
                type: string
                description: Maximum number of characters in the attachment key.
                example: '1'
              DomainValues:
                type: string
                description: Allowed key values.
                example: 7,9,10
      example:
        Name: Ingredients
        IsRequired: true
        IsActive: true
        Domains:
        - FieldName: Sauce
          MaxCaracters: ''
          DomainValues: '[1-2]#9[1-1][1]basic;#11[0-1][1]basic'
        - FieldName: Toppings
          MaxCaracters: ''
          DomainValues: '[0-10]#8[0-3][0]medium;#9[0-3][0]medium;#10[0-3][0]medium;#11[0-3][0]medium;#36[0-3][0]medium;#37[0-3][0]medium;#38[0-3][0]medium'
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
