openapi: 3.2.0
info:
  title: VTex Catalog Specification Field Value API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Specification Field Value
paths:
  /api/catalog_system/pvt/specification/fieldValue/{fieldValueId}:
    get:
      tags:
      - Specification Field Value
      summary: VTex Get specification field value
      description: 'Retrieves details from a specification field''s value by this value''s ID.

        >⚠️ This is a legacy endpoint. We recommend using Get specification value instead.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationsGetFieldValue
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: fieldValueId
        in: path
        description: Specification value ID.
        required: true
        style: simple
        schema:
          type: string
          example: '143'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                FieldValueId: 143
                FieldId: 34
                Name: Cotton
                Text: Cotton fibers
                IsActive: true
                Position: 100
              schema:
                type: object
                properties:
                  FieldValueId:
                    type: integer
                    format: int32
                    description: Specification field value ID.
                  FieldId:
                    type: integer
                    description: Specification field ID.
                  Name:
                    type: string
                    description: Specification field value name.
                  Text:
                    type: string
                    description: Specification field value Description.
                  IsActive:
                    type: boolean
                    description: Defines if the specification field Value is active (`true`) or inactive (`false`).
                  Position:
                    type: integer
                    format: int32
                    description: Specification field value position.
      deprecated: false
  /api/catalog_system/pub/specification/fieldvalue/{fieldId}:
    get:
      tags:
      - Specification Field Value
      summary: VTex Get specification values by specification field ID
      description: 'Gets a list of all specification values from a specification field by this field''s ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationsValuesByFieldId
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: fieldId
        in: path
        description: Specification field ID.
        required: true
        style: simple
        schema:
          type: integer
          example: 34
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetSpecFieldValue'
              example:
              - FieldValueId: 52
                Value: 0 a 6 meses
                IsActive: true
                Position: 1
              - FieldValueId: 53
                Value: 1 a 2 anos
                IsActive: true
                Position: 4
              - FieldValueId: 54
                Value: 3 a 4 anos
                IsActive: true
                Position: 3
              - FieldValueId: 55
                Value: 5 a 6 anos
                IsActive: true
                Position: 2
              - FieldValueId: 56
                Value: 7 a 8 anos
                IsActive: true
                Position: 5
              - FieldValueId: 57
                Value: 9 a 10 anos
                IsActive: true
                Position: 6
              - FieldValueId: 58
                Value: Acima de 10 anos
                IsActive: true
                Position: 7
      deprecated: false
  /api/catalog_system/pvt/specification/fieldValue:
    post:
      tags:
      - Specification Field Value
      summary: VTex Create specification field value
      description: 'Creates a specification field value by the specification field''s ID.

        >⚠️ This is a legacy endpoint. We recommend using Create specification value instead.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationsInsertFieldValue
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecificationsInsertFieldValueRequest'
            example:
              FieldId: 34
              Name: Cotton
              Text: Cotton fibers
              IsActive: true
              Position: 100
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                FieldValueId: 143
                FieldId: 34
                Name: Cotton
                Text: Cotton fibers
                IsActive: true
                Position: 100
              schema:
                type: object
                properties:
                  FieldValueId:
                    type: integer
                    format: int32
                    description: Specification field value ID.
                  FieldId:
                    type: integer
                    description: Specification field ID.
                  Name:
                    type: string
                    description: Specification field value name.
                  Text:
                    type: string
                    description: Specification field value description.
                  IsActive:
                    type: boolean
                    description: Defines if the specification field value is active (`true`) or inactive (`false`).
                  Position:
                    type: integer
                    format: int32
                    description: Specification field value position.
      deprecated: false
    put:
      tags:
      - Specification Field Value
      summary: VTex Update specification field value
      description: 'Updates a specification field value by the specification field''s ID.

        >⚠️ This is a legacy endpoint. We recommend using Update specification field value instead.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationsUpdateFieldValue
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecificationsUpdateFieldValueRequest'
            example:
              FieldId: 1
              FieldValueId: 143
              Name: Cotton
              Text: Cotton fibers
              IsActive: true
              Position: 100
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: Field Value Updated
              schema:
                type: string
                description: Status of the request.
      deprecated: false
components:
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  schemas:
    SpecificationsInsertFieldValueRequest:
      required:
      - FieldId
      - Name
      - Text
      - IsActive
      - Position
      type: object
      properties:
        FieldId:
          type: integer
          format: int32
          description: Specification field ID.
        Name:
          type: string
          description: Specification field value name.
        Text:
          type: string
          description: Specification field value description.
        IsActive:
          type: boolean
          description: Defines if the specification field value is active (`true`) or inactive (`false`).
        Position:
          type: integer
          format: int32
          description: Specification field value position.
      example:
        FieldValueId: 143
        FieldId: 34
        Name: Cotton
        Text: Cotton fibers
        IsActive: true
        Position: 100
    SpecificationsUpdateFieldValueRequest:
      required:
      - FieldId
      - Name
      - Text
      - IsActive
      - Position
      type: object
      properties:
        FieldId:
          type:
          - integer
          - 'null'
          description: Specification field ID.
        Name:
          type: string
          description: Specification field value name.
        Text:
          type:
          - string
          - 'null'
          description: Specification field value description.
        IsActive:
          type: boolean
          description: Defines if the specification field value is active (`true`) or inactive (`false`).
        Position:
          type: integer
          format: int32
          description: Specification field position.
      example:
        FieldId: 1
        FieldValueId: 143
        Name: Cotton
        Text: Cotton fibers
        IsActive: true
        Position: 100
    GetSpecFieldValue:
      required:
      - FieldValueId
      - Value
      - IsActive
      - Position
      type: object
      properties:
        FieldValueId:
          type: integer
          format: int32
          description: Specification field value ID.
        Value:
          type: string
          description: Specification field value.
        IsActive:
          type: boolean
          description: Defines if the specification field is active (`true`) or inactive (`false`).
        Position:
          type: integer
          format: int32
          description: Specification field value position.
      example:
        FieldValueId: 52
        Value: 0 a 6 meses
        IsActive: true
        Position: 1
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
