openapi: 3.2.0
info:
  title: VTex Subscriptions API (v3) Plans API
  description: '

    A **Subscription** is a list of items (SKUs) tied to certain recurring purchase settings:


    - User profile

    - Address

    - Payment method

    - Frequency

    - Cycle


    Once you have [configured subscriptions](https://help.vtex.com/tutorial/how-to-configure-subscriptions%20--1FA9dfE7vJqxBna9Nft5Sj) in your store, the Subscriptions API allows you to create, manage and monitor your customers'' subscriptions.


    ![image](https://user-images.githubusercontent.com/77292838/213024675-9407863b-0c55-4282-9442-306352716abe.png)


    To read more about the Subscriptions feature, check our article [How Subscription works](https://help.vtex.com/tutorial/how-subscriptions-work--frequentlyAskedQuestions_4453).'
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Plans
paths:
  /api/rns/pvt/plans:
    get:
      tags:
      - Plans
      summary: VTex List plans
      description: List plans filtering by some arguments.
      parameters:
      - name: periodicity
        in: query
        description: Filter plans by available periodicity
        schema:
          type:
          - string
          - 'null'
      - name: interval
        in: query
        description: Filter plans by available interval
        schema:
          type:
          - string
          - 'null'
      - name: page
        in: query
        description: Page used for pagination
        schema:
          type: integer
          format: int32
          default: 1
      - name: size
        in: query
        description: Page size used for pagination
        schema:
          type: integer
          format: int32
          default: 15
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: Requested plans
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorePlan'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorePlan'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StorePlan'
  /api/rns/pvt/plans/{id}:
    get:
      tags:
      - Plans
      summary: VTex Get plan details
      description: This endpoint retrieves a specific plan by its ID.
      parameters:
      - name: id
        in: path
        description: Id from the desired plan
        required: true
        schema:
          type:
          - string
          - 'null'
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: Requested plan
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StorePlan'
            application/json:
              schema:
                $ref: '#/components/schemas/StorePlan'
            text/json:
              schema:
                $ref: '#/components/schemas/StorePlan'
components:
  schemas:
    Frequency:
      type: object
      properties:
        periodicityAsString:
          type:
          - string
          - 'null'
        periodicity:
          $ref: '#/components/schemas/Periodicity'
        interval:
          type: integer
          format: int32
      additionalProperties: false
    Periodicity:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      type: integer
      format: int32
    StorePlan:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        frequencies:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Frequency'
      additionalProperties: false
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
