openapi: 3.2.0
info:
  title: VTex Catalog Supplier API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Supplier
paths:
  /api/catalog/pvt/supplier:
    post:
      tags:
      - Supplier
      summary: VTex Create Supplier
      description: 'Creates a new Supplier.

        ## Request body example


        ```json

        {

        "Name": "Supplier",

        "CorporateName": "TopStore",

        "StateInscription": "",

        "Cnpj": "33304981001272",

        "Phone": "3333333333",

        "CellPhone": "4444444444",

        "CorportePhone": "5555555555",

        "Email": "email@email.com",

        "IsActive": true

        }

        ```


        ## Response body example


        ```json

        {

        "Id": 1,

        "Name": "Supplier",

        "CorporateName": "TopStore",

        "StateInscription": "",

        "Cnpj": "33304981001272",

        "Phone": "3333333333",

        "CellPhone": "4444444444",

        "CorportePhone": "5555555555",

        "Email": "email@email.com",

        "IsActive": true

        }

        ```'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
      operationId: postApiCatalogPvtSupplier
      x-operation-id-source: derived
  /api/catalog/pvt/supplier/{supplierId}:
    put:
      tags:
      - Supplier
      summary: VTex Update Supplier
      description: 'Updates general information of an existing Supplier.

        ## Request body example


        ```json

        {

        "Name": "Supplier",

        "CorporateName": "TopStore",

        "StateInscription": "",

        "Cnpj": "33304981001272",

        "Phone": "3333333333",

        "CellPhone": "4444444444",

        "CorportePhone": "5555555555",

        "Email": "email@email.com",

        "IsActive": true

        }

        ```


        ## Response body example


        ```json

        {

        "Id": 1,

        "Name": "Supplier",

        "CorporateName": "TopStore",

        "StateInscription": "",

        "Cnpj": "33304981001272",

        "Phone": "3333333333",

        "CellPhone": "4444444444",

        "CorportePhone": "5555555555",

        "Email": "email@email.com",

        "IsActive": true

        }

        ```'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: supplierId
        in: path
        required: true
        description: Supplier's unique numerical identifier.
        schema:
          type: integer
          example: 1
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupplierRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupplierResponse'
      operationId: putApiCatalogPvtSupplierBySupplierId
      x-operation-id-source: derived
    delete:
      tags:
      - Supplier
      summary: VTex Delete Supplier
      description: Deletes an existing Supplier.
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: supplierId
        in: path
        required: true
        description: Supplier's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtSupplierBySupplierId
      x-operation-id-source: derived
components:
  schemas:
    SupplierRequest:
      type: object
      required:
      - Name
      - CorporateName
      - StateInscription
      - Cnpj
      - Phone
      - CellPhone
      - CorportePhone
      - Email
      - IsActive
      properties:
        Name:
          type: string
          description: Supplier Name.
          example: Supplier
        CorporateName:
          type: string
          description: Supplier Corporate Name.
          example: TopStore
        StateInscription:
          type: string
          description: State Inscription.
          example: '123456'
        Cnpj:
          type: string
          description: Corporate legal ID.
          example: '33304981001272'
        Phone:
          type: string
          description: Supplier Phone.
          example: '3333333333'
        CellPhone:
          type: string
          description: Supplier Cellphone.
          example: '4444444444'
        CorportePhone:
          type: string
          description: Supplier Corporate Phone.
          example: '5555555555'
        Email:
          type: string
          description: Supplier email.
          example: email@email.com
        IsActive:
          type: boolean
          description: Defines if the Supplier is active (`true`) or not (`false`).
          example: false
    SupplierResponse:
      type: object
      properties:
        Id:
          type: integer
          description: Supplier unique identifier code.
          example: 123
        Name:
          type: string
          description: Supplier Name.
          example: Supplier
        CorporateName:
          type: string
          description: Supplier Corporate Name.
          example: TopStore
        StateInscription:
          type: string
          description: State Inscription.
          example: '123456'
        Cnpj:
          type: string
          description: Corporate legal ID.
          example: '33304981001272'
        Phone:
          type: string
          description: Supplier Phone.
          example: '3333333333'
        CellPhone:
          type: string
          description: Supplier Cellphone.
          example: '4444444444'
        CorportePhone:
          type: string
          description: Supplier Corporate Phone.
          example: '5555555555'
        Email:
          type: string
          description: Supplier email.
          example: email@email.com
        IsActive:
          type: boolean
          description: Defines if the Supplier is active (`true`) or not (`false`).
          example: false
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
