openapi: 3.2.0
info:
  title: VTex Catalog Sales Channel API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Sales Channel
paths:
  /api/catalog_system/pvt/saleschannel/list:
    get:
      tags:
      - Sales Channel
      summary: VTex Get Sales channel list
      description: 'Retrieves a list with details about the store''s sales channels.

        ## Response body example


        ```json

        [

        {

        "Id": 1,

        "Name": "Loja Principal",

        "IsActive": true,

        "ProductClusterId": null,

        "CountryCode": "BRA",

        "CultureInfo": "pt-BR",

        "TimeZone": "E. South America Standard Time",

        "CurrencyCode": "BRL",

        "CurrencySymbol": "R$",

        "CurrencyLocale": 1046,

        "CurrencyFormatInfo": {

        "CurrencyDecimalDigits": 1,

        "CurrencyDecimalSeparator": ",",

        "CurrencyGroupSeparator": ".",

        "CurrencyGroupSize": 3,

        "StartsWithCurrencySymbol": true

        },

        "Origin": null,

        "Position": 2,

        "ConditionRule": null,

        "CurrencyDecimalDigits": 1

        }

        ]

        ```'
      operationId: SalesChannelList
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Id:
                      type: integer
                      description: Sales channel unique identifier.
                      example: 1
                    Name:
                      type: string
                      description: Sales channel name.
                      example: Loja Principal
                    IsActive:
                      type: boolean
                      description: Defines if the Sales channel is active (`true`) or not (`false`).
                    ProductClusterId:
                      type:
                      - integer
                      - 'null'
                      description: Product Cluster ID, if the Sales channel has releated product Cluster.
                      example: null
                    CountryCode:
                      type: string
                      description: Country Code in ISO 3166-1 alfa-3 Standard.
                      example: BRA
                    CultureInfo:
                      type: string
                      description: Language Country code in LCIDstring Standard.
                      example: pt-BR
                    TimeZone:
                      type: string
                      description: Name of Time Zone.
                      example: E. South America Standard Time
                    CurrencyCode:
                      type: string
                      description: Currency Code in ISO 4217 standard.
                      example: BRL
                    CurrencySymbol:
                      type: string
                      description: Currency symbol.
                      example: R$
                    CurrencyLocale:
                      type: integer
                      description: Currency Locale Code in LCID standard.
                      example: 1046
                    CurrencyFormatInfo:
                      type: object
                      description: Object with currency format.
                      properties:
                        CurrencyDecimalDigits:
                          type: integer
                          description: Quantity of Currency Decimal Digits.
                          example: 1
                        CurrencyDecimalSeparator:
                          type: string
                          description: Defines which Currency Decimal Separator will be applied.
                          example: ','
                        CurrencyGroupSeparator:
                          type: string
                          description: Defines which Currency Group Separator will be applied.
                          example: .
                        CurrencyGroupSize:
                          type: integer
                          description: Define how many characters will be grouped.
                          example: 3
                        StartsWithCurrencySymbol:
                          type: boolean
                          description: Defines if all prices will be initiated with Currency Symbol (`true`) or not (`false`).
                          example: true
                    Origin:
                      type:
                      - string
                      - 'null'
                      description: Origin of products in the Sales channel.
                      example: null
                    Position:
                      type:
                      - integer
                      - 'null'
                      description: Defines the position on index.
                      example: 1
                    ConditionRule:
                      type:
                      - string
                      - 'null'
                      description: Defines what is the conditional rule to activate de Sales channel.
                      example: approved=true
                    CurrencyDecimalDigits:
                      type: integer
                      description: Quantity of Currency Decimal Digits.
                      example: 1
      deprecated: false
  /api/catalog_system/pub/saleschannel/{salesChannelId}:
    get:
      tags:
      - Sales Channel
      summary: VTex Get Sales channel by ID
      description: 'Retrieves a specific sales channel by its ID.


        ## Response body example


        ```json

        {

        "Id": 1,

        "Name": "Loja Principal",

        "IsActive": true,

        "ProductClusterId": null,

        "CountryCode": "BRA",

        "CultureInfo": "pt-BR",

        "TimeZone": "E. South America Standard Time",

        "CurrencyCode": "BRL",

        "CurrencySymbol": "R$",

        "CurrencyLocale": 1046,

        "CurrencyFormatInfo": {

        "CurrencyDecimalDigits": 1,

        "CurrencyDecimalSeparator": ",",

        "CurrencyGroupSeparator": ".",

        "CurrencyGroupSize": 3,

        "StartsWithCurrencySymbol": true

        },

        "Origin": null,

        "Position": 2,

        "ConditionRule": null,

        "CurrencyDecimalDigits": 1

        }

        ```'
      operationId: SalesChannelbyId
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: salesChannelId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
          example: '1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    description: Sales channel unique identifier.
                    example: 1
                  Name:
                    type: string
                    description: Sales channel name.
                    example: Loja Principal
                  IsActive:
                    type: boolean
                    description: Defines if the Sales channel is active (`true`) or not (`false`).
                  ProductClusterId:
                    type:
                    - integer
                    - 'null'
                    description: Product Cluster ID, if the Sales channel has releated product Cluster.
                    example: null
                  CountryCode:
                    type: string
                    description: Country Code in ISO 3166-1 alfa-3 Standard.
                    example: BRA
                  CultureInfo:
                    type: string
                    description: Language Country code in LCIDstring Standard.
                    example: pt-BR
                  TimeZone:
                    type: string
                    description: Name of Time Zone.
                    example: E. South America Standard Time
                  CurrencyCode:
                    type: string
                    description: Currency Code in ISO 4217 standard.
                    example: BRL
                  CurrencySymbol:
                    type: string
                    description: Currency symbol.
                    example: R$
                  CurrencyLocale:
                    type: integer
                    description: Currency Locale Code in LCID standard.
                    example: 1046
                  CurrencyFormatInfo:
                    type: object
                    description: Object with currency format.
                    properties:
                      CurrencyDecimalDigits:
                        type: integer
                        description: Quantity of Currency Decimal Digits.
                        example: 1
                      CurrencyDecimalSeparator:
                        type: string
                        description: Defines which Currency Decimal Separator will be applied.
                        example: ','
                      CurrencyGroupSeparator:
                        type: string
                        description: Defines which Currency Group Separator will be applied.
                        example: .
                      CurrencyGroupSize:
                        type: integer
                        description: Define how many characters will be grouped.
                        example: 3
                      StartsWithCurrencySymbol:
                        type: boolean
                        description: Defines if all prices will be initiated with Currency Symbol (`true`) or not (`false`).
                        example: true
                  Origin:
                    type:
                    - string
                    - 'null'
                    description: Origin of products in the Sales channel.
                    example: null
                  Position:
                    type:
                    - integer
                    - 'null'
                    description: Defines the position on index.
                    example: 1
                  ConditionRule:
                    type:
                    - string
                    - 'null'
                    description: Defines what is the conditional rule to activate de Sales channel.
                    example: approved=true
                  CurrencyDecimalDigits:
                    type: integer
                    description: Quantity of Currency Decimal Digits.
                    example: 1
      deprecated: false
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
