openapi: 3.2.0
info:
  title: VTex Catalog Specification Value API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Specification Value
paths:
  /api/catalog/pvt/specificationvalue/{specificationValueId}:
    get:
      tags:
      - Specification Value
      summary: VTex Get specification value
      description: 'Retrieves general information about a specification value.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: specificationValueId
        in: path
        required: true
        description: Specification value's unique numerical identifier.
        schema:
          type: integer
          example: 143
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                FieldValueId: 143
                FieldId: 34
                Name: Cotton
                Text: Cotton fibers
                IsActive: true
                Position: 100
              schema:
                type: object
                properties:
                  FieldValueId:
                    type: integer
                    format: int32
                    description: Specification field value ID.
                  FieldId:
                    type: integer
                    description: Specification field ID.
                  Name:
                    type: string
                    description: Specification field value name.
                  Text:
                    type: string
                    description: Specification field value description.
                  IsActive:
                    type: boolean
                    description: Defines if the specification field value is active (`true`) or inactive (`false`).
                  Position:
                    type: integer
                    format: int32
                    description: Specification field value position.
      operationId: getApiCatalogPvtSpecificationvalueBySpecificationValueId
      x-operation-id-source: derived
    put:
      tags:
      - Specification Value
      summary: VTex Update specification value
      description: 'Updates a new specification value for a category.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: specificationValueId
        in: path
        required: true
        description: ' specification value''s unique numerical identifier.'
        schema:
          type: integer
          example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - FieldId
              - Name
              properties:
                FieldId:
                  type: integer
                  description: Specification ID associated with this specification value.
                  example: 193
                Name:
                  type: string
                  description: Specification value name.
                  example: Metal
                Text:
                  type:
                  - string
                  - 'null'
                  deprecated: true
                  description: Specification value text.
                IsActive:
                  type: boolean
                  description: Enable (`true`) or disable (`false`) specification value.
                  example: true
                Position:
                  type: integer
                  description: The position of the value to be shown on product registration page (`/admin/Site/Produto.aspx`).
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                FieldValueId: 360
                FieldId: 193
                Name: Metal
                Text: null
                IsActive: true
                Position: 1
              schema:
                type: object
                properties:
                  FieldValueId:
                    type: integer
                    description: Specification value ID.
                  FieldId:
                    type: integer
                    description: Specification field ID associated with this specification value.
                  Name:
                    type: string
                    description: Specification value name.
                  Text:
                    type:
                    - string
                    - 'null'
                    deprecated: true
                    description: Specification value text.
                  IsActive:
                    type: boolean
                    description: Enable (`true`) or disable (`false`) specification value.
                  Position:
                    type: integer
                    description: The position of the value to be shown on product registration page (`/admin/Site/Produto.aspx`).
      operationId: putApiCatalogPvtSpecificationvalueBySpecificationValueId
      x-operation-id-source: derived
  /api/catalog/pvt/specificationvalue:
    post:
      tags:
      - Specification Value
      summary: VTex Create specification value
      description: 'Creates a new specification value for a category.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - FieldId
              - Name
              properties:
                FieldId:
                  type: integer
                  description: Specification field ID associated with this specification value.
                  example: 193
                Name:
                  type: string
                  description: Specification value name.
                  example: Metal
                Text:
                  type:
                  - string
                  - 'null'
                  deprecated: true
                  description: Specification value text.
                IsActive:
                  type: boolean
                  description: Enable (`true`) or disable (`false`) specification value.
                  example: true
                Position:
                  type: integer
                  description: The position of the value to be shown on product registration page (`/admin/Site/Produto.aspx`).
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                FieldValueId: 360
                FieldId: 193
                Name: Metal
                Text: null
                IsActive: true
                Position: 1
              schema:
                type: object
                properties:
                  FieldValueId:
                    type: integer
                    description: Specification value ID.
                  FieldId:
                    type: integer
                    description: Specification field ID associated with this specification value.
                  Name:
                    type: string
                    description: Specification value name.
                  Text:
                    type:
                    - string
                    - 'null'
                    deprecated: true
                    description: Specification value text.
                  IsActive:
                    type: boolean
                    description: Enable (`true`) or disable (`false`) specification value.
                  Position:
                    type: integer
                    description: The position of the value to be shown on product registration page (`/admin/Site/Produto.aspx`).
      operationId: postApiCatalogPvtSpecificationvalue
      x-operation-id-source: derived
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
