openapi: 3.2.0
info:
  title: VTex Catalog Legacy Collection API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Legacy Collection
paths:
  /api/catalog/pvt/collection/{collectionId}:
    get:
      tags:
      - Legacy Collection
      summary: VTex Get collection by ID
      description: '>⚠️ There are two ways to configure collections, through Legacy CMS Portal or using the Beta Collection module. This endpoint is compatible with collections configured through the Legacy CMS Portal.


        Retrieves general information of a Collection.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Collection | **Read Collections** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: collectionId
        in: path
        required: true
        description: Collection's unique numerical identifier.
        schema:
          type: integer
          example: 151
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    description: Collection ID.
                  Name:
                    type: string
                    description: Collection name.
                  Description:
                    type:
                    - string
                    - 'null'
                    description: Collection description.
                  Searchable:
                    type: boolean
                    description: Defines if the collection is searchable or not.
                  Highlight:
                    type: boolean
                    description: Defines if the collection is highlighted or not.
                  DateFrom:
                    type: string
                    description: Initial value date for the collection.
                  DateTo:
                    type: string
                    description: Final value date for the collection.
                  TotalProducts:
                    type: integer
                    description: Total quantity of products in the collection.
                  Type:
                    type: string
                    description: '[Type of the collection](https://help.vtex.com/en/tutorial/collection-types--5tKnhh8tMGIrVL7Fqirq7n).'
              example:
                Id: 150
                Name: Test
                Description: Winter outfits.
                Searchable: true
                Highlight: false
                DateFrom: '2017-09-27T10:47:00'
                DateTo: '2017-09-27T10:47:00'
                TotalProducts: 150
                Type: Manual
      operationId: getApiCatalogPvtCollectionByCollectionId
      x-operation-id-source: derived
    put:
      tags:
      - Legacy Collection
      summary: VTex Update Collection
      description: '>⚠️ There are two ways to configure collections, through Legacy CMS Portal or using the Beta Collection module. This endpoint is compatible with collections configured through the Legacy CMS Portal.


        Updates a previously created Collection.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Collection | **Write Collections** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: collectionId
        in: path
        required: true
        description: Collection's unique numerical identifier.
        schema:
          type: integer
          example: 151
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - Name
              - Searchable
              - Highlight
              - DateFrom
              - DateTo
              properties:
                Name:
                  type: string
                  description: Collection name.
                  example: Test
                Searchable:
                  type: boolean
                  description: Defines if the collection is searchable or not.
                  example: true
                Highlight:
                  type: boolean
                  description: Defines if the collection is highlighted or not.
                  example: false
                DateFrom:
                  type: string
                  description: Initial value date for the collection.
                  example: '2017-09-27T10:47:00'
                DateTo:
                  type: string
                  description: Final value date for the collection.
                  example: '2017-09-27T10:47:00'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    description: Collection ID.
                  Name:
                    type: string
                    description: Collection name.
                  Description:
                    type:
                    - string
                    - 'null'
                    description: Collection description.
                  Searchable:
                    type: boolean
                    description: Defines if the collection is searchable or not.
                  Highlight:
                    type: boolean
                    description: Defines if the collection is highlighted or not.
                  DateFrom:
                    type: string
                    description: Initial value date for the collection.
                  DateTo:
                    type: string
                    description: Final value date for the collection.
                  TotalProducts:
                    type: integer
                    description: Total quantity of products in the collection.
                  Type:
                    type: string
                    description: '[Type of the collection](https://help.vtex.com/en/tutorial/collection-types--5tKnhh8tMGIrVL7Fqirq7n).'
              example:
                Id: 150
                Name: Test
                Description: Winter outfits.
                Searchable: true
                Highlight: false
                DateFrom: '2017-09-27T10:47:00'
                DateTo: '2017-09-27T10:47:00'
                TotalProducts: 150
                Type: Manual
      operationId: putApiCatalogPvtCollectionByCollectionId
      x-operation-id-source: derived
    delete:
      tags:
      - Legacy Collection
      summary: VTex Delete Collection
      description: '>⚠️ There are two ways to configure collections, through Legacy CMS Portal or using the Beta Collection module. This endpoint is compatible with collections configured through the Legacy CMS Portal.


        Deletes a previously existing Collection.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Collection | **Write Collections** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: collectionId
        in: path
        required: true
        description: Collection's unique numerical identifier.
        schema:
          type: integer
          example: 151
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtCollectionByCollectionId
      x-operation-id-source: derived
  /api/catalog/pvt/collection:
    post:
      tags:
      - Legacy Collection
      summary: VTex Create collection
      description: '>⚠️ There are two ways to configure collections, through Legacy CMS Portal or using the Beta Collection module. This endpoint is compatible with collections configured through the Legacy CMS Portal.


        Creates a new collection.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Collection | **Write Collections** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - Name
              - Searchable
              - Highlight
              - DateFrom
              - DateTo
              properties:
                Name:
                  type: string
                  description: Collection name.
                  example: Test
                Searchable:
                  type: boolean
                  description: Defines if the collection is searchable or not.
                  example: true
                Highlight:
                  type: boolean
                  description: Defines if the collection is highlighted or not.
                  example: false
                DateFrom:
                  type: string
                  description: Initial value date for the collection.
                  example: '2017-09-27T10:47:00'
                DateTo:
                  type: string
                  description: Final value date for the collection.
                  example: '2017-09-27T10:47:00'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    description: Collection ID.
                  Name:
                    type: string
                    description: Collection name.
                  Description:
                    type:
                    - string
                    - 'null'
                    description: Collection description.
                  Searchable:
                    type: boolean
                    description: Defines if the collection is searchable or not.
                  Highlight:
                    type: boolean
                    description: Defines if the collection is highlighted or not.
                  DateFrom:
                    type: string
                    description: Initial value date for the collection.
                  DateTo:
                    type: string
                    description: Final value date for the collection.
                  TotalProducts:
                    type: integer
                    description: Total quantity of products in the collection.
                  Type:
                    type: string
                    description: '[Type of the collection](https://help.vtex.com/en/tutorial/collection-types--5tKnhh8tMGIrVL7Fqirq7n).'
              example:
                Id: 150
                Name: Test
                Description: Winter outfits.
                Searchable: true
                Highlight: false
                DateFrom: '2017-09-27T10:47:00'
                DateTo: '2017-09-27T10:47:00'
                TotalProducts: 150
                Type: Manual
      operationId: postApiCatalogPvtCollection
      x-operation-id-source: derived
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
