openapi: 3.2.0
info:
  title: VTex Subscriptions API (v3) Reports API
  description: 'A **Subscription** is a list of items (SKUs) tied to certain recurring purchase settings:


    - User profile

    - Address

    - Payment method

    - Frequency

    - Cycle


    Once you have configured subscriptions in your store, the Subscriptions API allows you to create, manage and monitor your customers'' subscriptions.


    !image


    To read more about the Subscriptions feature, check our article How Subscription works.'
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Reports
paths:
  /api/rns/pvt/reports:
    get:
      tags:
      - Reports
      summary: VTex List report templates
      description: List all report templates available.
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: Requested report templates
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionReport'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionReport'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionReport'
      operationId: getApiRnsPvtReports
      x-operation-id-source: derived
  /api/rns/pvt/reports/{reportName}/documents/{documentId}:
    get:
      tags:
      - Reports
      summary: VTex Get report document details
      description: Retrieve a specific report document by its Id.
      parameters:
      - name: reportName
        in: path
        required: true
        description: Name of the report
        schema:
          type:
          - string
          - 'null'
      - name: documentId
        in: path
        required: true
        description: Id from the desired report document
        schema:
          type:
          - string
          - 'null'
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: Requested report document
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReportResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
      operationId: getApiRnsPvtReportsByReportNameDocumentsByDocumentId
      x-operation-id-source: derived
  /api/rns/pvt/reports/{reportName}/documents:
    post:
      tags:
      - Reports
      summary: VTex Generate report
      description: 'This endpoint creates a new report in the format of a CSV file and sends it via email. You can generate one of the following reports:


        - subscriptionsWithStatus


        - subscriptionsScheduledBetweenDate


        - subscriptionsUpdatedBetweenDate


        - subscriptionsCreatedBetweenDate


        - executionsBetweenDate'
      parameters:
      - name: reportName
        in: path
        required: true
        description: "Name of the type of report in wish to generate. The following values are accepted: \n\n - `subscriptionsWithStatus` \n\n - `subscriptionsScheduledBetweenDate` \n\n - `subscriptionsUpdatedBetweenDate` \n\n - `subscriptionsCreatedBetweenDate` \n\n - `executionsBetweenDate`"
        schema:
          type:
          - string
          - 'null'
      - name: email
        in: query
        description: The report is sent to the email in this field.
        schema:
          type: string
          default: receiver@email.com
      - name: beginDate
        in: query
        description: Start date of the report with the format `yyyy-mm-dd`. This field is required for any type of report.
        schema:
          type: string
          default: '2022-09-01'
      - name: endDate
        in: query
        description: End date of the report with the format `yyyy-mm-dd`. This field is required for any type of report.
        schema:
          type: string
          default: '2022-10-01'
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      responses:
        '200':
          description: Requested report
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ReportResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'
      operationId: postApiRnsPvtReportsByReportNameDocuments
      x-operation-id-source: derived
components:
  schemas:
    SubscriptionReport:
      type: object
      properties:
        account:
          type:
          - string
          - 'null'
        key:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        description:
          type:
          - string
          - 'null'
        requesterEmail:
          type:
          - string
          - 'null'
        entity:
          type:
          - string
          - 'null'
        schema:
          type:
          - string
          - 'null'
        query:
          type:
          - string
          - 'null'
        params:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/SubscriptionReportParam'
      additionalProperties: false
    ReportResponse:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
        finished:
          type: boolean
        recordsProcessed:
          type: integer
          format: int64
          readOnly: true
        recordsSum:
          type:
          - integer
          - 'null'
          format: int64
        startDate:
          type:
          - string
          - 'null'
          format: date-time
        lastUpdateTime:
          type:
          - string
          - 'null'
          format: date-time
        completedDate:
          type:
          - string
          - 'null'
          format: date-time
        errorCount:
          type:
          - integer
          - 'null'
          format: int64
        percentageProcessed:
          type: integer
          format: int64
        enqueueDate:
          type:
          - string
          - 'null'
          format: date-time
        email:
          type:
          - string
          - 'null'
        canceled:
          type: boolean
        outputType:
          type:
          - string
          - 'null'
        zipped:
          type: boolean
        linkToDownload:
          type:
          - string
          - 'null'
        lastErrorMessage:
          type:
          - string
          - 'null'
        statusMessage:
          type:
          - string
          - 'null'
          readOnly: true
      additionalProperties: false
    SubscriptionReportParam:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
        value: {}
      additionalProperties: false
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
