openapi: 3.2.0
info:
  title: VTex Logistics Scheduled Delivery API
  description: '>Check the Fulfillment onboarding guide. We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about fulfillment and is organized by focusing on the developer''s journey.


    Logistics or fulfillment is the module responsible for shipping calculation and inventory management.


    The variable `{{environment}}` can be filled with `vtexcommercestable` or `vtexcommercebeta`, depending on the environment you want to test.'
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Scheduled Delivery
paths:
  /api/logistics/pvt/configuration/carriers/{carrierId}/getdayofweekblocked:
    get:
      tags:
      - Scheduled Delivery
      summary: VTex Retrieve blocked delivery windows
      description: 'Lists all blocked delivery windows of your store''s shipping policies, searching by carrier ID.


        > Note that, while most of our API endpoints return time fields in UTC, this endpoint returns **Scheduled Delivery** related time fields adjusted to the configured time zone of the account.'
      operationId: RetrieveBlockedDeliveryWindows
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: carrierId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
      deprecated: false
  /api/logistics/pvt/configuration/carriers/{carrierId}/adddayofweekblocked:
    post:
      tags:
      - Scheduled Delivery
      summary: VTex Add blocked delivery windows
      description: 'Adds blocked delivery windows for your store''s shipping policies.


        > Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account.'
      operationId: AddBlockedDeliveryWindows
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: carrierId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              type: string
              example: '"2016-08-09T08:00:00"'
            example: '"2016-08-09T08:00:00"'
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/configuration/carriers/{carrierId}/removedayofweekblocked:
    post:
      tags:
      - Scheduled Delivery
      summary: VTex Remove blocked delivery windows
      description: 'Removes the blocked delivery windows set to your store''s shipping policies.


        > Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account.'
      operationId: RemoveBlockedDeliveryWindows
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: carrierId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              type: string
              example: '"2016-08-09T08:00:00"'
            example: '"2016-08-09T08:00:00"'
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics-capacity/resources/carrier@{capacityType}@{shippingPolicyId}/time-frames:
    get:
      tags:
      - Scheduled Delivery
      summary: VTex Search capacity reservations in time range
      description: 'Get information on all capacity reservations made to scheduled delivery windows in a given time range.


        > Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account.


        > Note that the combined string `carrier@{capacityType}@{shippingPolicyId}` can be referred to as a "resource" in the API''s messages.'
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/vnd.vtex.availability.v1+json
      - name: capacityType
        in: path
        description: How the delivery capacity is measured as defined in the shipping policy. Capacity can be measured by maximum number of orders (`"orders_quantity"`) or SKUs (`"skus_quantity"`).
        required: true
        style: simple
        schema:
          type: string
          example: '{{capacityType}}'
      - name: shippingPolicyId
        in: path
        description: ID of shipping policy to search.
        required: true
        style: simple
        schema:
          type: string
          example: '{{shippingPolicyId}}'
      - name: rangeStart
        in: query
        description: Starting date of time range
        required: true
        style: form
        schema:
          type: string
          example: yyyy-mm-dd
      - name: rangeEnd
        in: query
        description: End date of time range.
        required: true
        style: form
        schema:
          type: string
          example: yyyy-mm-dd
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                id: 2021-05-03F1300T1700
                resourceId: carrier@skus_quantity@143e313
                startDate: '2021-05-03T13:00:00+00:00'
                endDate: '2021-05-03T17:00:59+00:00'
                ownMaxCapacity: 10
                resourceMaxCapacity: 10
                reservedValue: 6
                reservations:
                - id: reservation-01
                  value: 4
                - id: reserva-02
                  value: 2
                log:
                - when: '2021-04-29T15:56:09.1732357+00:00'
                  who: ''
                  why: Reservation `reservation-01` with 2.0 units.
                  what: Unblocked
                - when: '2021-04-29T17:29:11.9250354+00:00'
                  who: ''
                  why: Reservation `reserva-02` with 4.0 units.
                  what: Unblocked
      deprecated: false
      operationId: getApiLogisticsCapacityResourcesCarrier@{capacityType}@{shippingPolicyId}TimeFrames
      x-operation-id-source: derived
  ? /api/logistics-capacity/resources/carrier@{capacityType}@{shippingPolicyId}/time-frames/{windowDay}F{windowStartTime}T{windowEndTime}
  : get:
      tags:
      - Scheduled Delivery
      summary: VTex Get capacity reservation usage by window
      description: 'Retrieves capacity usage of a specific scheduled delivery reservation window.


        > Note that, while most of our API endpoints return time fields in UTC, this endpoint returns time adjusted to the configured time zone of the account.


        > Note that the combined string `carrier@{capacityType}@{shippingPolicyId}` can be referred to as a "resource" in the API''s messages.'
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/vnd.vtex.availability.v1+json
      - name: capacityType
        in: path
        description: How the delivery capacity is measured as defined in the shipping policy. Capacity can be measured by maximum number of orders (`"orders_quantity"`) or SKUs (`"skus_quantity"`).
        required: true
        style: simple
        schema:
          type: string
          example: '{{capacityType}}'
      - name: shippingPolicyId
        in: path
        description: ID of shipping policy to search.
        required: true
        style: simple
        schema:
          type: string
          example: '{{shippingPolicyId}}'
      - name: windowDay
        in: path
        description: Day of the specific scheduled delivery window to be consulted for reservations.
        required: true
        style: simple
        schema:
          type: string
          example: yyyy-mm-dd
      - name: windowStartTime
        in: path
        description: Start time of specific scheduled delivery window to be consulted for reservations.
        required: true
        style: simple
        schema:
          type: string
          example: hhmm
      - name: windowEndTime
        in: path
        description: End time of specific scheduled delivery window to be consulted for reservations.
        required: true
        style: simple
        schema:
          type: string
          example: hhmm
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                id: 2021-05-03F1300T1700
                resourceId: carrier@skus_quantity@143e313
                startDate: '2021-05-03T13:00:00+00:00'
                endDate: '2021-05-03T17:00:59+00:00'
                ownMaxCapacity: 10
                resourceMaxCapacity: 10
                reservedValue: 4
                reservations:
                - id: reservation-01
                  value: 4
                log:
                - when: '2021-04-29T15:56:09.1732357+00:00'
                  who: ''
                  why: Reservation `reservation-01` with 4 units.
                  what: Unblocked
      deprecated: false
      operationId: getApiLogisticsCapacityResourcesCarrier@{capacityType}@{shippingPolicyId}TimeFramesByWindowDay}F{windowStartTime}T{windowEndTime
      x-operation-id-source: derived
components:
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
