openapi: 3.2.0
info:
  title: VTex Catalog SKU Service Type API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: SKU Service Type
paths:
  /api/catalog/pvt/skuservicetype:
    post:
      tags:
      - SKU Service Type
      summary: VTex Create SKU service type
      description: 'Creates a new SKU service type.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU type management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKUServiceTypeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SKUServiceTypeResponse'
              example:
                Id: 2
                Name: Test API SKU services
                IsActive: true
                ShowOnProductFront: true
                ShowOnCartFront: true
                ShowOnAttachmentFront: true
                ShowOnFileUpload: true
                IsGiftCard: true
                IsRequired: true
      operationId: postApiCatalogPvtSkuservicetype
      x-operation-id-source: derived
  /api/catalog/pvt/skuservicetype/{skuServiceTypeId}:
    get:
      tags:
      - SKU Service Type
      summary: VTex Get SKU service type
      description: 'Retrieves information about an existing SKU service type.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU type management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuServiceTypeId
        in: path
        required: true
        description: SKU service type unique identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SKUServiceTypeResponse'
              example:
                Id: 2
                Name: Test API SKU services
                IsActive: true
                ShowOnProductFront: true
                ShowOnCartFront: true
                ShowOnAttachmentFront: true
                ShowOnFileUpload: true
                IsGiftCard: true
                IsRequired: true
      operationId: getApiCatalogPvtSkuservicetypeBySkuServiceTypeId
      x-operation-id-source: derived
    put:
      tags:
      - SKU Service Type
      summary: VTex Update SKU service type
      description: 'Updates an existing SKU service type.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU type management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuServiceTypeId
        in: path
        required: true
        description: SKU service type unique identifier.
        schema:
          type: integer
          example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKUServiceTypeRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SKUServiceTypeResponse'
              example:
                Id: 2
                Name: Test API SKU services
                IsActive: true
                ShowOnProductFront: true
                ShowOnCartFront: true
                ShowOnAttachmentFront: true
                ShowOnFileUpload: true
                IsGiftCard: true
                IsRequired: true
      operationId: putApiCatalogPvtSkuservicetypeBySkuServiceTypeId
      x-operation-id-source: derived
    delete:
      tags:
      - SKU Service Type
      summary: VTex Delete SKU service type
      description: 'Deletes an existing SKU service type.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU type management** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuServiceTypeId
        in: path
        required: true
        description: SKU service type unique identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtSkuservicetypeBySkuServiceTypeId
      x-operation-id-source: derived
components:
  schemas:
    SKUServiceTypeRequest:
      type: object
      required:
      - Name
      - IsActive
      - ShowOnProductFront
      - ShowOnCartFront
      - ShowOnAttachmentFront
      - ShowOnFileUpload
      - IsGiftCard
      - IsRequired
      properties:
        Name:
          type: string
          description: SKU service type name. Maximum of 100 characters.
          default: Test API Sku Services
        IsActive:
          type: boolean
          description: Defines if the SKU service type is active or not.
          default: true
        ShowOnProductFront:
          type: boolean
          description: Deprecated field.
          example: false
          deprecated: true
        ShowOnCartFront:
          type: boolean
          description: Defines if the SKU service type is displayed on the cart screen.
          example: false
        ShowOnAttachmentFront:
          type: boolean
          description: Defines if the SKU service type has an attachment.
          example: false
        ShowOnFileUpload:
          type: boolean
          description: Defines if the SKU service type can be associated with an attachment or not.
          example: false
        IsGiftCard:
          type: boolean
          description: Defines if the SKU service type is displayed as a Gift Card.
          example: false
        IsRequired:
          type: boolean
          description: Defines if the SKU service type is mandatory.
          example: false
    SKUServiceTypeResponse:
      type: object
      properties:
        Id:
          type: integer
          description: SKU service type ID.
          example: 2
        Name:
          type: string
          description: SKU service type name. Maximum of 100 characters.
          example: Test API Sku Services
        IsActive:
          type: boolean
          description: Defines if the SKU service type is active or not.
          example: true
        ShowOnProductFront:
          type: boolean
          description: Deprecated field.
          example: false
          deprecated: true
        ShowOnCartFront:
          type: boolean
          description: Defines if the SKU service type is displayed on the cart screen.
          example: false
        ShowOnAttachmentFront:
          type: boolean
          description: Defines if the SKU service type has an attachment.
          default: false
        ShowOnFileUpload:
          type: boolean
          description: Defines if the SKU service type can be associated with an attachment or not.
          default: false
        IsGiftCard:
          type: boolean
          description: Defines if the SKU service type is displayed as a Gift Card.
          default: false
        IsRequired:
          type: boolean
          description: Defines if the SKU service type is mandatory.
          default: false
      example:
        Id: 2
        Name: Test API SKU services
        IsActive: true
        ShowOnProductFront: true
        ShowOnCartFront: true
        ShowOnAttachmentFront: true
        ShowOnFileUpload: true
        IsGiftCard: true
        IsRequired: true
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
