openapi: 3.2.0
info:
  title: VTex Reviews and Ratings Rating API
  description: Reviews & Ratings is a VTEX IO app that allows shoppers to submit reviews and ratings for products, and view them while navigating the store.
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.myvtex.com
  description: VTEX server URL
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: storecomponents
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Rating
paths:
  /reviews-and-ratings/api/rating/{productId}:
    get:
      tags:
      - Rating
      summary: VTex Get product rating
      description: 'Retrieves the rating of a product.

        ## Permissions


        This endpoint does not require permissions.'
      operationId: GetProductRating
      parameters:
      - name: productId
        in: path
        description: Product ID.
        required: true
        style: simple
        schema:
          type: string
          example: '1'
      - name: Content-Type
        in: header
        description: Describes the type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Accept
        in: header
        description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: Response body object.
                type: object
                properties:
                  average:
                    description: Average rating of the product.
                    type: number
                  totalCount:
                    description: Total amount of ranting of the product.
                    type: number
              example:
                average: 3.86
                totalCount: 7
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                description: Response body object.
                properties:
                  code:
                    type: string
                    description: Error type code.
                  message:
                    type: string
                    description: Error message.
                  source:
                    type: string
                    description: Error source.
                  requestId:
                    type: string
                    description: VTEX request identifier.
              example:
                code: NotFound
                message: apiexamples.myvtex.com not found
                source: Vtex.Kube.Router.WebApi
                requestId: b49522afa7c94b76885450f652be7bfc
      deprecated: false
components:
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
