openapi: 3.2.0
info:
  title: VTex Logistics Holidays API
  description: '>Check the Fulfillment onboarding guide. We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about fulfillment and is organized by focusing on the developer''s journey.


    Logistics or fulfillment is the module responsible for shipping calculation and inventory management.


    The variable `{{environment}}` can be filled with `vtexcommercestable` or `vtexcommercebeta`, depending on the environment you want to test.'
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
tags:
- name: Holidays
paths:
  /api/logistics/pvt/configuration/holidays/{holidayId}:
    put:
      tags:
      - Holidays
      summary: VTex Create/update holiday
      description: Creates or updates holidays through holiday ID.
      operationId: Create/UpdateHoliday
      parameters:
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: holidayId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              title: Create/UpdateHolidayRequest
              required:
              - name
              - startDate
              type: object
              properties:
                name:
                  type: string
                startDate:
                  type: string
              example:
                name: Natal
                startDate: '2016-12-25'
            example:
              name: Natal
              startDate: '2016-12-25'
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
    get:
      tags:
      - Holidays
      summary: VTex List holiday by ID
      description: Lists holiday's information by holiday ID.
      operationId: HolidayById
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: holidayId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
    delete:
      tags:
      - Holidays
      summary: VTex Delete holiday
      description: Deletes given holidays set up in your store.
      operationId: Holiday
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: holidayId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/configuration/holidays:
    get:
      tags:
      - Holidays
      summary: VTex List all holidays
      description: Lists information of all holidays.
      operationId: AllHolidays
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
components:
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
