openapi: 3.2.0
info:
  title: VTex Catalog Gift List API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Gift List
paths:
  /api/addon/pvt/giftlist/get/{listId}:
    get:
      tags:
      - Gift List
      summary: VTex Get Gift list
      description: Retrieves information about a Gift list by its ID.
      operationId: GetGiftList
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: listId
        in: path
        required: true
        description: Gift list unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: Object with information about the Gift list.
                example:
                  giftListId: 1
                  name: My list
                  userId: 010956A4-A74A-4375-8B7B-3B3B7B89B483
                  clientId: 3
                  fileId: null
                  giftListTypeId: 1
                  giftListTypeName: Lista de Casamento
                  giftCardId: 2
                  message: mensageeeem
                  urlFolder: lili
                  dateCreated: '2011-05-04T13:23:00'
                  profileSystemUserAddressName: CASA
                  profileSystemUserId: 010956A4-A74A-4375-8B7B-3B3B7B89B483
                  eventDate: '2012-12-21T00:00:00'
                  eventLocation: ''
                  eventCity: ''
                  eventState: ''
                  telemarketingId: null
                  telemarketingObservation: ''
                  IsPublic: false
                  isActive: false
                  shipsToOwner: false
                  isAddressOk: true
                  version: 1
                  giftCardRechargeSkuId: null
                  memberNames: sei lá
                  giftListMembers: []
                  giftListSkuIds: []
                  address: null
                  fileUrl: null
                properties:
                  giftListId:
                    type: integer
                    description: Gift list ID.
                    example: 1
                  name:
                    type: string
                    description: Gift list name.
                    example: My list
                  userId:
                    type: string
                    description: User ID.
                    example: a6e7d995-e884-409d-911f-36b25c40169a
                  fileId:
                    type:
                    - integer
                    - 'null'
                    description: File ID.
                    example: 155233
                  giftListTypeId:
                    type: integer
                    description: Gift list Type ID.
                    example: 1
                  giftListTypeName:
                    type: string
                    description: Gift list Type name.
                    example: Wedding list
                  giftCardId:
                    type: integer
                    description: Gift Card ID.
                    example: 2
                  message:
                    type: string
                    description: Gift list message.
                    example: This is a gift list for my wedding.
                  urlFolder:
                    type: string
                    description: Slug of the gift list that will be part of its URL.
                    example: myweddinglist
                  dateCreated:
                    type: string
                    description: Date when the gift list was created.
                    example: '2013-10-31T19:03:00'
                  profileSystemUserAddressName:
                    type: string
                    description: Name of the user's address.
                    example: CASA
                  profileSystemUserId:
                    type: string
                    description: User ID on Profile System.
                    example: a6e7d995-e884-409d-911f-36b25c40169a
                  eventDate:
                    type: string
                    description: Date of the event associated with the Gift list.
                    example: '2014-07-20T00:00:00'
                  eventLocation:
                    type: string
                    description: Location of the event associated with the Gift list.
                    example: Botafogo
                  eventCity:
                    type: string
                    description: City of the event associated with the Gift list.
                    example: Rio de Janeiro
                  eventState:
                    type: string
                    description: State of the event associated with the Gift list.
                    example: RJ
                  telemarketingId:
                    type:
                    - integer
                    - 'null'
                    description: Telemarketing ID.
                    example: 1
                  telemarketingObservation:
                    type: string
                    description: Telemarketing observation.
                    example: ''
                  IsPublic:
                    type: boolean
                    description: Defines if the gift list is public.
                    example: true
                  isActive:
                    type: boolean
                    description: Defines if the gift list is active.
                    example: true
                  shipsToOwner:
                    type: boolean
                    description: Defines if items purchased from the gift list will be shipped to the owner of the gift list.
                    example: false
                  isAddressOk:
                    type: boolean
                    description: Validates the address of the gift list.
                    example: false
                  version:
                    type: integer
                    description: Version of the gift list.
                    example: 1
                  giftCardRechargeSkuId:
                    type:
                    - integer
                    - 'null'
                    description: ID of the SKU that recharges the gift card.
                    example: 1
                  memberNames:
                    type: string
                    description: Name of the members of the gift list.
                    example: Rafael Villa-Verde
                  giftListMembers:
                    type: array
                    description: Array of members of the gift list.
                    items:
                      type: object
                      description: Object with information about each gift list member.
                      properties:
                        giftListMemberId:
                          type: integer
                          description: Gift list member ID.
                        giftListId:
                          type: integer
                          description: Gift list ID.
                        userId:
                          type: string
                          description: User ID.
                        clientId:
                          type:
                          - string
                          - 'null'
                          description: Client ID.
                        title:
                          type:
                          - string
                          - 'null'
                          description: Title of the Gift list member.
                        name:
                          type: string
                          description: Name of the Gift list member.
                        surname:
                          type: string
                          description: Surname of the Gift list member.
                        isAdmin:
                          type: boolean
                          description: Defines if the Gift list member is an administrator of the Gift list or not.
                        isActive:
                          type: boolean
                          description: Defines if the Gift list user is active or not.
                        text1:
                          type:
                          - string
                          - 'null'
                          description: Complementary text.
                        text2:
                          type:
                          - string
                          - 'null'
                          description: Complementary text.
                      example:
                        giftListMemberId: 1
                        giftListId: 2
                        userId: 010956A4-A74A-4375-8B7B-3B3B7B89B483
                        clientId: null
                        title: null
                        name: Rafael
                        surname: Villa-Verde
                        isAdmin: true
                        isActive: true
                        text1: null
                        text2: null
                  giftListSkuIds:
                    type: array
                    description: Array with the IDs of SKUs that are part of the gift list.
                    items:
                      type: string
                      description: SKU ID.
                  address:
                    type:
                    - string
                    - 'null'
                    description: Address of the gift list.
                    example: Botafogo
                  fileUrl:
                    type:
                    - string
                    - 'null'
                    description: File URL.
                    example: /arquivos/ids/155233-800-800/gl-0_635266293044683588.jpg
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
