openapi: 3.2.0
info:
  title: VTex Orders Feed V2 (Deprecated) API
  description: Each purchase a customer makes in your store generates an order on VTEX.
  contact: {}
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey:
  - '{{appKey}}'
  appToken:
  - '{{appToken}}'
tags:
- name: Feed V2 (Deprecated)
paths:
  /api/oms/pvt/feed/orders/status:
    get:
      tags:
      - Feed V2 (Deprecated)
      summary: VTex Get feed order status
      description: Get feed order status (deprecated)
      operationId: Getfeedorderstatus
      parameters:
      - name: maxLot
        in: query
        description: Maximum lot.
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: '{{maxLot}}'
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        description: Type of the content being sent
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
components:
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
