openapi: 3.2.0
info:
  title: VTex Catalog SKU Service Value API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: SKU Service Value
paths:
  /api/catalog/pvt/skuservicevalue:
    post:
      tags:
      - SKU Service Value
      summary: VTex Create SKU service value
      description: 'Creates an SKU service value for an existing SKU service type.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU Services** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKUServiceValueRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SKUServiceValueResponse'
              example:
                Id: 2
                SkuServiceTypeId: 2
                Name: Test ServiceValue API
                Value: 10.5
                Cost: 10.5
      operationId: postApiCatalogPvtSkuservicevalue
      x-operation-id-source: derived
  /api/catalog/pvt/skuservicevalue/{skuServiceValueId}:
    get:
      tags:
      - SKU Service Value
      summary: VTex Get SKU service value
      description: 'Retrieves an existing SKU service value.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU Services** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuServiceValueId
        in: path
        required: true
        description: SKU service value unique identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SKUServiceValueResponse'
              example:
                Id: 2
                SkuServiceTypeId: 2
                Name: Test ServiceValue API
                Value: 10.5
                Cost: 10.5
      operationId: getApiCatalogPvtSkuservicevalueBySkuServiceValueId
      x-operation-id-source: derived
    put:
      tags:
      - SKU Service Value
      summary: VTex Update SKU service value
      description: 'Updates an existing SKU service value.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU Services** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuServiceValueId
        in: path
        required: true
        description: SKU service value unique identifier.
        schema:
          type: integer
          example: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKUServiceValueRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SKUServiceValueResponse'
              example:
                Id: 2
                SkuServiceTypeId: 2
                Name: Test ServiceValue API
                Value: 10.5
                Cost: 10.5
      operationId: putApiCatalogPvtSkuservicevalueBySkuServiceValueId
      x-operation-id-source: derived
    delete:
      tags:
      - SKU Service Value
      summary: VTex Delete SKU service value
      description: 'Deletes an existing SKU service value.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Commercial | **SKU Services** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuServiceValueId
        in: path
        required: true
        description: SKU service value unique identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtSkuservicevalueBySkuServiceValueId
      x-operation-id-source: derived
components:
  schemas:
    SKUServiceValueResponse:
      type: object
      required:
      - SkuServiceTypeId
      - Name
      - Value
      - Cost
      properties:
        Id:
          type: integer
          description: SKU service value ID.
          example: 2
        SkuServiceTypeId:
          type: integer
          description: SKU service type ID.
          example: 2
        Name:
          type: string
          description: SKU service value name. Maximum of 100 characters.
          example: Test ServiceValue API
        Value:
          type: number
          description: SKU service value value.
          example: 10.5
        Cost:
          type: number
          description: SKU service value cost.
          example: 10.5
      example:
        Id: 2
        SkuServiceTypeId: 2
        Name: Test ServiceValue API
        Value: 10.5
        Cost: 10.5
    SKUServiceValueRequest:
      type: object
      required:
      - SkuServiceTypeId
      - Name
      - Value
      - Cost
      properties:
        SkuServiceTypeId:
          type: integer
          description: SKU service type ID.
          example: 2
        Name:
          type: string
          description: SKU service value name. Maximum of 100 characters.
          example: Test ServiceValue API
        Value:
          type: number
          description: SKU service value value.
          example: 10.5
        Cost:
          type: number
          description: SKU service value cost.
          example: 10.5
      example:
        SkuServiceTypeId: 2
        Name: Test ServiceValue API
        Value: 10.5
        Cost: 10.5
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
