openapi: 3.2.0
info:
  title: VTex Catalog Product Indexing API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Product Indexing
paths:
  /api/catalog_system/pvt/products/GetIndexedInfo/{productId}:
    get:
      tags:
      - Product Indexing
      summary: VTex Get product Indexed Information
      description: 'Retrieve details of a product''s Indexed Information in XML format.

        ## Response body example


        ```xml

        "

        \n

        \n


        true

        0

        2


        *


        instanceId:394dbdc8-b1f4-4dea-adfa-1ec104f3bfe1

        productId:1


        \n

        \n"

        ```'
      operationId: IndexedInfo
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: productId
        in: path
        description: Product's unique numerical identifier.
        required: true
        style: simple
        schema:
          type: string
          example: '1'
      responses:
        '200':
          description: OK
          content:
            xml: {}
      deprecated: false
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
